//
//  DataManager.swift
//  Asean
//
//  Created by Ricki Bin Yamin on 15/07/20.
//  Copyright © 2020 Ricki Bin Yamin. All rights reserved.
//

import UIKit

class DataManager {
    static var shared = DataManager()
    
    func fetchData() -> [Country] {
        return [
            Country(country: "Indonesia", capital: "Jakarta", independence: "17 Agustus 1945", photos: [UIImage(named: "IndonesiaPhoto"), UIImage(named: "IndonesiaPhoto1"), UIImage(named: "IndonesiaPhoto2"), UIImage(named: "IndonesiaPhoto3"), UIImage(named: "IndonesiaPhoto4"), UIImage(named: "IndonesiaPhoto5")], flag: UIImage(named: "IndonesiaFlag"), semboyan: "Bhineka Tunggal Ika", nationalAnthem: "Indonesia Raya", languages: "Bahasa Indonesia dan 700+ Bahasa Daerah", language: "Bahasa", information: """
            Indonesia disebut juga dengan Republik Indonesia (RI) atau Negara Kesatuan Republik Indonesia (NKRI), adalah negara di Asia Tenggara yang dilintasi garis khatulistiwa dan berada di antara daratan benua Asia dan Australia, serta antara Samudra Pasifik dan Samudra Hindia. Indonesia adalah negara kepulauan terbesar di dunia yang terdiri dari 17.504 pulau. Nama alternatif yang biasa dipakai adalah Nusantara. Dengan populasi Hampir 270.054.853 jiwa pada tahun 2018, Indonesia adalah negara berpenduduk terbesar keempat di dunia dan negara yang berpenduduk Muslim terbesar di dunia, dengan lebih dari 230 juta jiwa.

            Bentuk negara Indonesia adalah negara kesatuan dan bentuk pemerintahan Indonesia adalah republik, dengan Dewan Perwakilan Rakyat, Dewan Perwakilan Daerah dan Presiden yang dipilih secara langsung.

            Ibu kota negara Indonesia adalah Jakarta. Indonesia berbatasan darat dengan Malaysia di Pulau Kalimantan, dengan Papua Nugini di Pulau Papua dan dengan Timor Leste di Pulau Timor. Negara tetangga lainnya adalah Singapura, Filipina, Australia, dan wilayah persatuan Kepulauan Andaman dan Nikobar di India.

            Sejarah Indonesia banyak dipengaruhi oleh bangsa lainnya. Kepulauan Indonesia menjadi wilayah perdagangan penting sejak abad ke-7, yaitu sejak berdirinya Kerajaan Sriwijaya, sebuah kemaharajaan Hindu-Buddha yang berpusat di Palembang. Kerajaan Sriwijaya ini menjalin hubungan agama dan perdagangan dengan Tiongkok dan India, juga dengan bangsa Arab. Kerajaan-kerajaan beragama Hindu dan/atau Buddha mulai tumbuh pada awal abad ke-4 hingga abad ke-13 Masehi, diikuti para pedagang dan ulama dari jazirah Arab yang membawa agama Islam sekitar abad ke-8 hingga abad ke-16, serta kedatangan bangsa Eropa pada akhir abad ke-15 yang saling bertempur untuk memonopoli perdagangan rempah-rempah Maluku semasa era penjelajahan samudra. Setelah berada di bawah penjajahan Belanda selama hampir 3 abad, Indonesia yang saat itu bernama Hindia Belanda menyatakan kemerdekaannya di akhir Perang Dunia II, tepatnya tanggal 17 Agustus 1945. Selanjutnya, Indonesia mendapat berbagai tantangan dan persoalan berat, mulai dari seringnya terjadi bencana alam, praktik korupsi yang masif, konflik sosial, gerakan separatisme, proses demokratisasi, dan periode pembangunan, perubahan dan perkembangan sosial-ekonomi-politik, serta modernisasi yang pesat.

            Dari Sabang di ujung Aceh sampai Merauke di tanah Papua, Indonesia terdiri dari berbagai suku bangsa, bahasa, dan agama. Berdasarkan rumpun bangsa (ras), Indonesia terdiri atas bangsa asli pribumi yakni Mongoloid Selatan/Austronesia dan Melanesia di mana bangsa Austronesia yang terbesar jumlahnya dan lebih banyak mendiami Indonesia bagian barat. Secara lebih spesifik, suku bangsa Jawa adalah suku bangsa terbesar dengan populasi mencapai 41,7% dari seluruh penduduk Indonesia. Semboyan nasional Indonesia, "Bhinneka tunggal ika" ("Berbeda-beda namun tetap satu"), bermakna keberagaman sosial-budaya yang membentuk satu kesatuan/negara. Selain memiliki populasi penduduk yang padat dan wilayah yang luas, Indonesia memiliki wilayah alam yang mendukung tingkat keanekaragaman hayati terbesar kedua di dunia.

            Indonesia merupakan anggota dari PBB dan satu-satunya anggota yang pernah keluar dari PBB, yaitu pada tanggal 7 Januari 1965, dan bergabung kembali pada tanggal 28 September 1966. Indonesia tetap dinyatakan sebagai anggota yang ke-60, keanggotaan yang sama sejak bergabungnya Indonesia pada tanggal 28 September 1950. Selain PBB, Indonesia juga negara anggota dari organisasi ASEAN, KAA, APEC, OKI, G-20 dan sebentar lagi akan menjadi anggota OECD.
            """
            ),
            Country(country: "Malaysia", capital: "Kuala Lumpur", independence: "31 Agustus 1957", photos: [UIImage(named: "MalaysiaPhoto"), UIImage(named: "MalaysiaPhoto1"), UIImage(named: "MalaysiaPhoto2"), UIImage(named: "MalaysiaPhoto3"), UIImage(named: "MalaysiaPhoto4"), UIImage(named: "MalaysiaPhoto5")], flag: UIImage(named: "MalaysiaFlag"), semboyan: "Bersekutu Bertambah Mutu", nationalAnthem: "Negaraku", languages: "Melayu, Inggris", language: "Melayu", information: """
            Malaysia adalah sebuah negara federal yang terdiri dari tiga belas negeri (negara bagian) dan tiga wilayah federal di Asia Tenggara dengan luas 329.847 km persegi. Ibu kotanya adalah Kuala Lumpur, sedangkan Putrajaya menjadi pusat pemerintahan federal. Jumlah penduduk negara ini mencapai 30.697.000 jiwa pada tahun 2015. Negara ini dipisahkan ke dalam dua kawasan — Malaysia Barat dan Malaysia Timur — oleh Kepulauan Natuna, wilayah Indonesia di Laut Tiongkok Selatan. Malaysia berbatasan dengan Thailand, Indonesia, Singapura, Brunei, dan Filipina. Negara ini terletak di dekat khatulistiwa dan beriklim tropika. Kepala negara Malaysia adalah seorang Raja atau seorang Sultan yang dipilih secara bergiliran setiap 5 tahun sekali, hanya negeri-negeri (negara bagian) yang diperintah oleh Raja/Sultan saja yang diperbolehkan mengirimkan wakilnya untuk menjadi Raja Malaysia. Raja Malaysia biasanya memakai gelar Sri Paduka Baginda Yang di-Pertuan Agong. dan pemerintahannya dikepalai oleh seorang Perdana Menteri. Model pemerintahan Malaysia mirip dengan sistem parlementer Westminster.

            Malaysia sebagai negara federal tidak pernah ada sampai tahun 1963. Sebelumnya, sekumpulan koloni didirikan oleh Britania Raya pada akhir abad ke-18, dan bagian barat Malaysia modern terdiri dari beberapa kerajaan yang terpisah-pisah. Kumpulan wilayah jajahan itu dikenal sebagai Malaya Britania hingga pembubarannya pada 1946, ketika kumpulan itu disusun kembali sebagai Uni Malaya. Karena semakin meluasnya tentangan, kumpulan itu lagi-lagi disusun kembali sebagai Federasi Malaya pada tahun 1948 dan kemudian meraih kemerdekaan pada 31 Agustus 1957.

            Pada 16 September 1963 sesuai dengan Resolusi Majelis Umum PBB 1514 dalam proses dekolonialisasi, Singapura, Sarawak, Borneo Utara atau yang sekarang lebih dikenal sebagai Sabah berubah menjadi negara bagian dari federasi bentukan baru yang bernama Malaysia termasuk dengan Federasi Malaya. dan pada 9 Agustus 1965 Singapura kemudian dikeluarkan dari Malaysia dan menjadi negara merdeka yang bernama Republik Singapura. saat tahun-tahun awal pembentukan federasi baru terdapat pula tentangan dari Filipina dan konflik militer dengan Indonesia.

            Bangsa-bangsa di Asia Tenggara mengalami ledakan ekonomi dan menjalani perkembangan yang cepat di penghujung abad ke-20. Pertumbuhan yang cepat pada dasawarsa 1980-an dan 1990-an, rata-rata 8% dari tahun 1991 hingga 1997, telah mengubah Malaysia menjadi negara industri baru. Karena Malaysia adalah salah satu dari tiga negara yang menguasai Selat Malaka, perdagangan internasional berperan penting di dalam ekonominya. Pada suatu ketika, Malaysia pernah menjadi penghasil timah, karet dan minyak kelapa sawit di dunia. Industri manufaktur memiliki pengaruh besar bagi ekonomi negara ini. Malaysia juga dipandang sebagai salah satu dari 18 negara berkeanekaragaman hayati terbesar di dunia.

            Bangsa Melayu menjadi bagian terbesar dari populasi Malaysia. Terdapat pula Ras Tionghoa Malaysia dan India Malaysia yang cukup besar. Bahasa Melayu dan Islam masing-masing menjadi bahasa dan agama resmi negara.

            Malaysia adalah anggota perintis ASEAN dan turut serta di berbagai organisasi internasional, seperti PBB. Sebagai bekas jajahan Inggris, Malaysia juga menjadi anggota Negara-Negara Persemakmuran. Malaysia juga menjadi anggota D-8 (Developing-8), yakni sebuah kesepakatan untuk kerja sama pembangunan delapan negara anggotanya: Bangladesh, Indonesia, Iran, Malaysia, Mesir, Nigeria, Pakistan, dan Turki.
            """
            ),
            Country(country: "Filipina", capital: "Manilla", independence: "12 Juni 1898", photos: [UIImage(named: "FilipinaPhoto"), UIImage(named: "FilipinaPhoto1"), UIImage(named: "FilipinaPhoto2"), UIImage(named: "FilipinaPhoto3"), UIImage(named: "FilipinaPhoto4"), UIImage(named: "FilipinaPhoto5"), UIImage(named: "FilipinaPhoto6")], flag: UIImage(named: "FilipinaFlag"), semboyan: "Maka-Diyos, Maka-Tao, Makakalikasan at Makabansa", nationalAnthem: "Lupang Hinirang", languages: "Aklanon, Bikol, Cebuano, Chavacano, Hilganyon, Ibanag, Ilocano, Ivatan, Kapampangan, Kinaray-a, Maguindanao, Maranao, Pangasinan, Sambal, Surigaonon, Tagalog, Tausug, Waray, Yakkan", language: "Filipino", information: """
            Filipina atau Republik Filipina (bahasa Tagalog: Republika ng Pilipinas) adalah sebuah negara republik di Asia Tenggara, sebelah utara Indonesia, dan Malaysia. Filipina merupakan sebuah negara kepulauan yang terletak di Lingkar Pasifik Barat, negara ini terdiri dari 7.641 pulau. Selama ribuan tahun, warga kepulauan Filipina, dan pekerja keras ini telah mengembangkan sistem cocok tanam Padi yang sangat maju, yang menyediakan makanan pokok bagi masyarakatnya.

            Filipina adalah negara paling maju di Benua Asia setelah Perang Dunia II, namun sejak saat itu telah tertinggal di belakang negara-negara lain akibat pertumbuhan ekonomi yang lemah, penyitaan kekayaan yang dilakukan pemerintah, korupsi yang luas, dan pengaruh-pengaruh neo-kolonial. Meskipun begitu, saat ini Filipina mengalami pertumbuhan ekonomi yang moderat, yang banyak disumbangkan dari pengiriman uang oleh pekerja-pekerja Filipina di luar negeri, dan sektor teknologi informasi yang sedang tumbuh pesat. Filipina sering kali dianggap sebagai satu-satunya negara di Benua Asia di mana pengaruh budaya Barat terasa sangat kuat.

            Masalah-masalah besar negara ini termasuk gerakan separatis Bangsamoro di sebelah selatan Filipina yaitu di region Mindanao, pemberontak-pemberontak dari Tentara Rakyat Baru (New People's Army) yang beraliran komunis di wilayah-wilayah pedesaan, kebijakan-kebijakan pemerintah yang sering tidak konsisten, tingkat kejahatan yang makin meningkat, dan kerusakan lingkungan seperti penebangan hutan, dan polusi laut. Filipina juga mengalami masalah banyaknya penduduk di daerah-daerah perkotaan akibat kurangnya lapangan pekerjaan di wilayah pedesaan, dan tingkat kelahiran yang tinggi.
            """
            ),
            Country(country: "Singapura", capital: "Singapura", independence: "9 Agustus 1965", photos: [UIImage(named: "SingapuraPhoto"), UIImage(named: "SingapuraPhoto1"), UIImage(named: "SingapuraPhoto2"), UIImage(named: "SingapuraPhoto3"), UIImage(named: "SingapuraPhoto4"), UIImage(named: "SingapuraPhoto5"), UIImage(named: "SingapuraPhoto6")], flag: UIImage(named: "SingapuraFlag"), semboyan: "Majulah Singapura", nationalAnthem: "Majulah Singapura", languages: "Melayu, Inggris, Mandarin, Tamil", language: "Melayu", information: """
            Singapura (nama resmi: Republik Singapura) adalah sebuah negara pulau di lepas ujung selatan Semenanjung Malaya, 137 kilometer (85 mil) di utara khatulistiwa di Asia Tenggara. Negara ini terpisah dari Malaysia oleh Selat Johor di utara, dan dari Kepulauan Riau, Indonesia oleh Selat Singapura di selatan. Singapura adalah pusat keuangan terdepan ketiga di dunia dan sebuah kota dunia kosmopolitan yang memainkan peran penting dalam perdagangan dan keuangan internasional. Pelabuhan Singapura adalah satu dari lima pelabuhan tersibuk di dunia.

            Singapura memiliki sejarah imigrasi yang panjang. Penduduknya yang beragam berjumlah kira-kira 6 juta jiwa, terdiri dari Orang Tionghoa, Melayu, India, Arab, berbagai keturunan Asia, dan Kaukasoid. 42% penduduk Singapura adalah orang asing yang bekerja dan menuntut ilmu di sana. Pekerja asing membentuk 50% dari sektor jasa. Negara ini adalah yang terpadat kedua di dunia setelah Monako. A.T. Kearney menyebut Singapura sebagai negara paling terglobalisasi di dunia dalam Indeks Globalisasi tahun 2006.

            Sebelum merdeka tahun 1965, Singapura adalah pelabuhan dagang yang beragam dengan PDB per kapita $511, tertinggi ketiga di Asia Timur pada saat itu. Setelah merdeka, investasi asing langsung dan usaha pemerintah untuk industrialisasi berdasarkan rencana bekas Deputi Perdana Menteri Dr. Goh Keng Swee membentuk ekonomi Singapura saat ini.

            Economist Intelligence Unit dalam "Indeks Kualitas Hidup" menempatkan Singapura pada peringkat satu kualitas hidup terbaik di Asia dan kesebelas di dunia. Singapura memiliki cadangan devisa terbesar kesembilan di dunia. Negara ini juga memiliki angkatan bersenjata yang maju.
            Setelah PDB-nya berkurang -6.8% pada kuartal ke-4 tahun 2009, Singapura mendapatkan gelar pertumbuhan ekonomi tercepat di dunia, dengan pertumbuhan PDB 17.9% pada pertengahan pertama 2010.
            """
            ),
            Country(country: "Thailand", capital: "Bangkok", independence: "5 Desember", photos: [UIImage(named: "ThailandPhoto"), UIImage(named: "ThailandPhoto1"), UIImage(named: "ThailandPhoto2"), UIImage(named: "ThailandPhoto3"), UIImage(named: "ThailandPhoto4"), UIImage(named: "ThailandPhoto5")], flag: UIImage(named: "ThailandFlag"), semboyan: "Chat, Satsana, Phra Maha Kasat", nationalAnthem: "Phleng Chat Thai", languages: "Melayu, Isam, Kam, Mueang, Pak Tai", language: "Thai", information: """
            Kerajaan Thai (nama resmi bahasa Thai: ราชอาณาจักรไทย Ratcha Anachak Thai, Raja Adnyacakra Thai; atau Prathēt Thai, Pradesa Thai), yang lebih sering disebut Thailand dalam bahasa Inggris, atau dalam bahasa aslinya Mueang Thai (dibaca: "meng-thai", sama dengan versi Inggrisnya, berarti "Negeri Thai"), adalah sebuah negara di Asia Tenggara yang berbatasan dengan Laos dan Kamboja di timur, Malaysia dan Teluk Siam di selatan, dan Myanmar dan Laut Andaman di barat. Kerajaan Thai dahulu dikenal sebagai Siam sampai tanggal 11 Mei 1949. Kata "Thai" (ไทย) berarti "kebebasan" dalam bahasa Thai, tetapi juga dapat merujuk kepada suku Thai, sehingga menyebabkan nama Siam masih digunakan di kalangan warga negara Thai terutama kaum minoritas Tionghoa dan Amerika.

            Orang-orang Thailand bermigrasi dari Cina barat daya ke daratan Asia Tenggara selama berabad-abad. Referensi paling awal yang diketahui tentang kehadiran mereka di wilayah tersebut berkaitan dengan pengasingan orang Siam di prasasti abad ke-12 di kompleks kuil Khmer Angkor Wat di Kamboja yang menyebut mereka "palsu" atau "perang lama". Daerah itu pernah dikuasai oleh berbagai pemerintah negara bagian India seperti Mon, Khmer Empire dan negara-negara Melayu, bersaing dengan negara-negara seperti Ngoenyang Thailand, Sukhothai, kerajaan Chiang Mai, Lan Na dan Ayutthaya juga saling bertentangan. Orang-orang Eropa tiba pada abad ke-16, dimulai dengan misi diplomatik Portugis ke Ayutthaya pada tahun 1511. Abad-abad berikutnya melihat berbagai kekuatan kolonial Eropa menduduki wilayah-wilayah di Indocina, di mana Thailand kehilangan sebagian besar wilayahnya oleh Prancis dan Inggris tetapi tetap satu-satunya. Negara-negara Asia Tenggara yang selamat dari pendudukan. Sejak pemerintahan Raja Rama IV pada pertengahan abad ke-19, Thailand telah berkampanye untuk memodernisasi negara sesuai dengan standar Barat. Hal ini menyebabkan transisi dari monarki monarki ke monarki konstitusional pada tahun 1932. Tetapi 60 tahun berikutnya melihat pemerintahan militer dan demokratis berganti, dengan kudeta terbaru pada Mei 2014.

            Thailand adalah anggota pendiri Asosiasi Negara-Negara Asia Tenggara (ASEAN) dan tetap menjadi sekutu utama Amerika Serikat. Meskipun ada perubahan kepemimpinan yang relatif sporadis, itu dianggap sebagai kekuatan regional di Asia Tenggara dan kekuatan menengah dalam urusan global. Dengan tingkat perkembangan manusia yang tinggi, ekonomi terbesar kedua di Asia Tenggara, dan terbesar ke-20 oleh PDB, Thailand digolongkan sebagai ekonomi industri baru; manufaktur, pertanian, dan pariwisata adalah sektor-sektor utama perekonomian.
            """
            ),
            Country(country: "Brunei Darussalam", capital: "Bandar Seri Begawan", independence: "1 Januari 1984", photos: [UIImage(named: "BruneiPhoto"), UIImage(named: "BruneiPhoto1"), UIImage(named: "BruneiPhoto2"), UIImage(named: "BruneiPhoto3"), UIImage(named: "BruneiPhoto4"), UIImage(named: "BruneiPhoto5")], flag: UIImage(named: "BruneiFlag"), semboyan: "Sentiasa membuat kebajikan dengan petunjuk Allah", nationalAnthem: "Allah Peliharakan Sultan", languages: "Melayu, Inggris", language: "Melayu", information: """
            Brunei Darussalam atau Brunei, nama resmi: Negara Brunei Darussalam, (bahasa Melayu: Negara Brunei Darussalam, Jawi: نڬارا بروني دارالسلام), adalah negara berdaulat di Asia Tenggara yang terletak di pantai utara pulau Kalimantan. Negara ini memiliki wilayah seluas 5.765 km² yang menempati pulau Borneo dengan garis pantai seluruhnya menyentuh Laut Tiongkok Selatan. Wilayahnya dipisahkan ke dalam dua negara bagian di Malaysia yaitu Sarawak dan Sabah.

            Saat ini, Brunei Darussalam memiliki Indeks Pembangunan Manusia tertinggi kedua di Asia Tenggara setelah Singapura, sehingga diklasifikasikan sebagai negara maju. Menurut Dana Moneter Internasional, Brunei memiliki produk domestik bruto per kapita terbesar kelima di dunia dalam keseimbangan kemampuan berbelanja. Sementara itu, Forbes menempatkan Brunei sebagai negara terkaya kelima dari 182 negara karena memiliki ladang minyak bumi dan gas alam yang luas. Selain itu, Brunei juga terkenal dengan kemakmurannya dan ketegasan dalam melaksanakan syariat Islam, baik dalam bidang pemerintahan maupun kehidupan bermasyarakat.
            """
            ),
            Country(country: "Vietnam", capital: "Hanoi", independence: "2 September 1945", photos: [UIImage(named: "VietnamPhoto"), UIImage(named: "VietnamPhoto1"), UIImage(named: "VietnamPhoto2"), UIImage(named: "VietnamPhoto3"), UIImage(named: "VietnamPhoto4"), UIImage(named: "VietnamPhoto5")], flag: UIImage(named: "VietnamFlag"), semboyan: "Độc lập – Tự do – Hạnh phúc", nationalAnthem: "Tiến Quân Ca", languages: "Vietnam", language: "Vietnam", information: """
            Vietnam (Bahasa Vietnam: Việt Nam Chữ Nôm: 越南[viət˨ næm˧]), bernama resmi Republik Sosialis Vietnam (Cộng Hòa Xã Hội Chủ Nghĩa Việt Nam 共和社會主義越南) adalah negara paling timur di Semenanjung Indochina di Asia Tenggara. Vietnam berbatasan dengan Republik Rakyat Tiongkok di sebelah utara, Laos di sebelah barat laut, Kamboja di sebelah barat daya dan di sebelah timur terbentang Laut China Selatan.

            Dengan populasi sekitar 84 juta jiwa, Vietnam adalah negara terpadat ke-13 di dunia. Vietnam termasuk di dalam grup ekonomi "Next Eleven"; menurut pemerintah, GDP Vietnam tumbuh sebesar 8.17% pada tahun 2006, negara dengan pertumbuhan tercepat kedua di Asia Timur dan pertama di Asia Tenggara. Pada akhir tahun 2007, menteri keuangan menyatakan pertumbuhan GDP Vietnam diperkirakan mencapai rekor tertinggi dalam sepuluh tahun terakhir sebesar 8.44%.

            Sejarah Vietnam dapat ditarik kembali ke 2500 tahun yang lalu, namun menurut legenda, bisa ditarik kembali ke 4000 tahun yang lalu. Vietnam, sejak abad 11 SM sampai abad 10 Masehi mayoritas berada di bawah kekuasaan kekaisaran Tiongkok. Tahun 939 M, Vietnam merdeka secara politis, dan mulai menggunakan Champa sebagai nama negara. Masa setelah ini dianggap sebagai masa pembangunan identitas kebangsaan Vietnam.
            """
            ),
            Country(country: "Laos", capital: "Vientiane", independence: "22 Oktober 1953", photos: [UIImage(named: "LaosPhoto"), UIImage(named: "LaosPhoto1"), UIImage(named: "LaosPhoto2"), UIImage(named: "LaosPhoto3"), UIImage(named: "LaosPhoto4"), UIImage(named: "LaosPhoto5")], flag: UIImage(named: "LaosFlag"), semboyan: "ສັນຕິພາບ ເອກະລາດ ປະຊາທິປະໄຕ ເອກະພາບ ວັດທະນະຖາວອນ", nationalAnthem: "ເພງຊາດລາວ", languages: "Lao, Prancis, Hmong, Khmu", language: "Lao", information: """
            Republik Demokratik Rakyat Laos adalah negara yang terkurung daratan di Asia Tenggara, berbatasan dengan Myanmar dan Republik Rakyat Tiongkok di sebelah barat laut, Vietnam di timur, Kamboja di selatan, dan Thailand di sebelah barat. Dari abad ke-14 hingga abad ke-18, negara ini disebut Lan Xang atau "Negeri Seribu Gajah".

            Laos adalah sebuah Negara Republik yang dikelilingi oleh daratan dan terletak di bagian utara Semenanjung Indochina. Laos berasal dari kata Lan Xang yang artinya kerajaan gajah. Negara ini adalah satu-satunya Negara di kawasan Asia Tenggara yang tidak memiliki pantai. Laos pernah dijajah oleh Prancis dan memperoleh kemerdekaan pada 22 Oktober 1953 dalam bentuk kerajaan. Sejak 2 Desember 1975 kerajaan Laos berubah menjadi Republik Laos. Laos adalah salah satu negara komunis dengan kepala pemerintahan berupa presiden yang bernama Choummaly Sayasone dan dibantu oleh perdana menteri yang bernama Bouasone Bouphavanh. Jika dilihat dari sudut pandang Geografi Politik, letak wilayah negara Laos yang tidak memiliki wilayah laut atau pantai dikenal dengan sebutan kawasan land-lock. Kondisi ini dianggap kurang menguntungkan dari segi pertahanan dan keamanan, khususnya dari serangan atau invasi bangsa lain. Negara Laos mempunyai lembah sungai subur sehingga banyak menghasilkan tanaman pertanian dan perkebunan, terutama padi, kopi, dan tembakau. Memiliki sumber-sumber tambang mineral, seperti timah, tembaga, emas, dan perak. Wilayahnya didominasi perbukitan dan pegunungan yang tertutup hutan lebat, sehingga menghasilkan kayu sebagai salah satu komoditasnya. Potensi Sosial Budaya Terdiri atas berbagai macam suku bangsa dengan berbagai macam budayanya, Masyarakatnya sebagian besar masih patuh pada tradisi, Memiliki bahasa nasional, yaitu bahasa Lao. Namun dalam kehidupan sehari-hari, selain bahasa nasionalnya masyarakat juga menggunakan bahasa Thai, Inggris, dan Prancis, Memiliki banyak bangunan bersejarah, terutama candi.

            Laos merupakan salah satu dari lima negara komunis yang ada di dunia. Luas wilayahnya sekitar 236.800 km2 dengan jumlah penduduk sekitar 6,6 juta jiwa. Bergabung dengan ASEAN sejak tahun 1997, tetapi negara yang terkurung daratan (landlocked country) ini baru membuka diri seluas-luasnya dengan negara lain pada tahun 2004. Langkah pertama yang diambil Laos dalam membuka diri adalah menarik modal asing. Laos berkali-kali merevisi undang-undang investasi asing, serta mengizinkan perusahaan asing mentransfer keuntungan keluar Laos. Investor asing juga diizinkan mendirikan perusahaan dengan modal murni atau patungan. Pemerintah Laos bahkan tidak memungut pajak terhadap perusahaan asing untuk lima tahun pertama bisnis di Laos.

            Untuk meningkatkan perekonomian, Laos menetapkan beberapa zona ekonomi, meningkatkan perdagangan internasional dan meningkatkan kerja sama regional. Mata pencaharian utama penduduk Laos pada sektor pertanian. Hasil pertanian utamanya berupa padi, jagung, tembakau, kapas, kopi dan buah jeruk. Daerah pertanian umumnya berada di daerah dataran rendah terutama di tepi sungai Mekong. Sungai Mekong merupakan urat nadi perekonomian Laos yang dimanfaatkan Laos untuk menghasilkan tenaga hydroelectric. Tenaga hydroelectric yang dihasilkan kemudian dijual oleh Laos ke negara tetangga seperti Vietnam dan Thailand. Pada tahun 2012, pemerintah Laos membentuk portal Laos Trade Center yang memberikan informasi terkait impor dan ekspor negara tersebut. Seiring keterbukaan ekonomi yang dilakukannya, perekonomian Laos meningkat sebesar 7,1% dari tahun 2001-2010 dan diharapkan meningkat sebesar 7,6% dari tahun 2011-2015. Bukan angka yang mustahil jika menilik pertumbuhan Gross Domestic Product (GDP) Laos pada tahun 2012 mencapai 8,1%.

            Awal sejarah Laos didominasi oleh Kerajaan Nanzhao, yang diteruskan pada abad ke-14 oleh kerajaan lokal Lan Xang yang berlangsung hingga abad ke-18, setelah Thailand menguasai kerajaan tersebut. Kemudian Prancis menguasai wilayah ini pada abad ke-19 dan menggabungkannya ke dalam Indochina Prancis pada 1893. Setelah penjajahan Jepang selama Perang Dunia II, negara ini memerdekakan diri pada 1949 dengan nama Kerajaan Laos di bawah pemerintahan Raja Sisavang Vong.

            Keguncangan politik di negara tetangganya Vietnam membuat Laos menghadapi Perang Indochina Kedua yang lebih besar (disebut juga Perang Rahasia) yang menjadi faktor ketidakstabilan yang memicu lahirnya perang saudara dan beberapa kali kudeta. Pada 1975 kaum komunis Pathet Lao yang didukung Uni Soviet dan komunis Vietnam menendang pemerintahan Raja Savang Vatthana dukungan Amerika Serikat dan Prancis. Setelah mengambil alih negara ini, mereka mengganti namanya menjadi Republik Demokratik Rakyat Laos yang masih berdiri hingga saat ini. Laos mempererat hubungannya dengan Vietnam dan mengendurkan larangan ekonominya pada akhir dekade 1980-an dan dimasukkan ke dalam ASEAN pada 1997.
            """
            ),
            Country(country: "Myanmar", capital: "Naypyidaw", independence: "4 Januari 1948", photos: [UIImage(named: "MyanmarPhoto"), UIImage(named: "MyanmarPhoto1"), UIImage(named: "MyanmarPhoto2"), UIImage(named: "MyanmarPhoto3"), UIImage(named: "MyanmarPhoto4"), UIImage(named: "MyanmarPhoto5"),], flag: UIImage(named: "MyanmarFlag"), semboyan: "-", nationalAnthem: "Kaba Ma Kyei", languages: "Burma, Kachin, Kayah, Karen, Chin, Mon, Rakhine, Shan", language: "Burma", information: """
            Republik Persatuan Myanmar (juga dikenal sebagai Birma, disebut "Burma" di dunia Barat) adalah sebuah negara berdaulat di Asia Tenggara. Myanmar berbatasan dengan India dan Bangladesh di sebelah barat, Thailand dan Laos di sebelah timur dan China di sebelah utara dan timur laut. Negara seluas 676.578 km² ini telah diperintah oleh pemerintahan militer sejak kudeta tahun 1988. Negara ini adalah negara berkembang dan memiliki populasi lebih dari 51 juta jiwa (sensus 2014). Ibu kota negara ini sebelumnya terletak di Yangon sebelum dipindahkan oleh pemerintahan junta militer ke Naypyidaw pada tanggal 7 November 2005. Myanmar telah bergabung sebagai anggota Perhimpunan Bangsa-Bangsa Asia Tenggara (ASEAN) sejak tahun 1997.

            Peradaban awal di Myanmar termasuk penduduk berbahasa Tibeto-Burma di Burma Utara dan Kerajaan Mon di Burma Selatan. Pada abad ke-9, orang Bamar memasuki lembah atas Sungai Irrawaddy, diikuti dengan didirikannya Kerajaan Pagan tahun 1050-an. Sejak saat itu, bahasa Burma, termasuk budaya dan Buddha Theravada perlahan-lahan menjadi dominan di negara ini. Kerajaan Pagan jatuh akibat invasi Mongol. Pada abad ke-16, setelah disatukan oleh Dinasti Taungoo, negara ini sesaat pernah menjadi kekaisaran terbesar dalam sejarah Asia Tenggara. Pada abad ke-19, Dinasti Konbaung menguasai daerah yang didalamnya termasuk wilayah Myanmar modern saat ini dan sesaat menguasai Manipur dan Assam. Inggris menguasai Myanmar setelah 3 Perang Anglo-Burma pada abad ke-19 dan negara ini kemudian menjadi koloni Inggris. Myanmar mendapatkan kemerdekaan tahun 1948, awalnya sebagai negara demokrasi, tetapi setelah kudeta tahun 1962, negara ini dikuasai militer.

            Setelah mereka, negara ini banyak mengalami kekerasan etnis. Selama periode ini, Perserikatan Bangsa-Bangsa dan banyak organisasi lainnya melaporkan terus terjadi pelanggaran hak asasi manusia secara konsisten dan sistematis. Pada tahun 2011, junta militer dibubarkan setelah pada tahun 2010 diadakan pemilihan umum, dan pemerintahan sipil dimulai. Hal ini, bersamaan dengan dilepasnya Aung San Suu Kyi dan tahanan politik lainnya, telah memperbaiki catatan hak asasi manusia dan hubungan luar negeri negara ini, memungkinkannya terbebas dari sanksi ekonomi. Namun, negara ini belum terbebas dari kritik akibat perlakuan pemerintah terhadap etnis minoritas. Pada pemilihan umum 2015, partai Aung San Suu Kyi menang mayoritas di parlemen. Namun, militer Myanmar tetap menjadi kekuatan utama di politik.

            Myanmar adalah negara yang kaya dengan giok, batu permata, minyak bumi, gas alam, dan mineral lain. Ketimpangan pendapatan di Myanmar adalah salah satu yang terlebar di dunia, karena sebagian besar ekonomi dikuasai oleh sebagian orang yang disokong militer. Per 2016, Myanmar menempati posisi 145 dari 188 negara di dunia menurut Indeks Pembangunan Manusia.
            """
            ),
            Country(country: "Kamboja", capital: "Pnom Penh", independence: "9 November 1953", photos: [UIImage(named: "KambojaPhoto"), UIImage(named: "KambojaPhoto1"), UIImage(named: "KambojaPhoto2"), UIImage(named: "KambojaPhoto3"), UIImage(named: "KambojaPhoto4"), UIImage(named: "KambojaPhoto5")], flag: UIImage(named: "KambojaFlag"), semboyan: "ជាតិ សាសនា ព្រះមហាក្សត្រ\nChéat, Sasna, Preăhmôhaksât", nationalAnthem: "Nokor Reach", languages: "Khmer, Cham, Prancis", language: "Khmer", information: """
            Kerajaan Kamboja adalah sebuah negara berbentuk monarki konstitusional di Asia Tenggara. Negara ini merupakan penerus Kekaisaran Khmer yang pernah menguasai seluruh Semenanjung Indochina antara abad ke-11 dan 14.

            Kamboja berbatasan dengan Thailand di sebelah barat, Laos di utara, Vietnam di timur, dan Teluk Thailand di selatan. Sungai Mekong dan Danau Tonle Sap melintasi negara ini.

            Menjelang kemerdekaannya, Negara Kesatuan Republik Indonesia banyak membantu negara Kamboja ini. Buku - buku taktik perang karangan perwira militer Indonesia banyak digunakan oleh militer Kamboja. Oleh karenanya, para calon perwira di militer Kamboja, wajib belajar dan dapat berbahasa Indonesia.
            """
            )
        ]
    }
}
